test checking for node versions

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -18,19 +18,28 @@ jobs:
       - name: Read Node version from .nvmrc
         id: node_version
         run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
+      
+      - name: Use Node.js
+        run: |
+          echo Node version: ${{env.NODE_VERSION}}
+          echo "Checking for Node.js installations..."
+          which node || echo "Node not found in PATH"
+          echo "Attempting to use default Node.js version..."
+          node -v || echo "Failed to get Node version"
+      
 
-      - uses: actions/setup-node@v4
-        with:
-          node-version: ${{ env.NODE_VERSION }}
+      # - uses: actions/setup-node@v4
+      #   with:
+      #     node-version: ${{ env.NODE_VERSION }}
 
-      - name: Install dependencies
-        run: npm ci
+      # - name: Install dependencies
+      #   run: npm ci
 
-      - name: Run typecheck
-        run: npm run typecheck
+      # - name: Run typecheck
+      #   run: npm run typecheck
 
-      - name: Run lint
-        run: npm run lint
+      # - name: Run lint
+      #   run: npm run lint
 
-      - name: Run unit test
-        run: npm run test
+      # - name: Run unit test
+      #   run: npm run test
